About page
Fetii1/shfkforina2023 pull request #15
Opened 2023-10-09 12:17 UTC by Fetii1

2023-10-10 09:08 UTC, Afan417 requested changes

2023-10-10 09:08 UTC, Afan417 commented on components/sections/FooterSection.js
> +    <div>
remove extra div, line 5 and 9

2023-10-10 09:08 UTC, Afan417 commented on components/sections/about/AboutText.js
> +export default function AboutText() {
you can move this inside ``AboutSection.js``

2023-10-10 09:08 UTC, Afan417 commented on components/sections/about/HeaderSection.js
> +}
Move this into ``components`` folder not sections
and make title dynamic as prop

      ``<h1 className="text-white font-bold pl-16">{title}</h1>``

2023-10-10 09:08 UTC, Afan417 commented on pages/about.js
>  export default function about() {
uppercase, ``About``

2023-10-10 09:13 UTC, Fetii1 commented on components/sections/FooterSection.js
> +    <div>
deleted the whole file... I have already added the footer in the Layout.js

2023-10-10 09:16 UTC, Fetii1 commented on components/sections/about/AboutText.js
> +export default function AboutText() {
This is in the /about page. the "AboutSection.js" is in the index.js page

2023-10-12 10:01 UTC, Afan417 requested changes

2023-10-12 10:01 UTC, Afan417 commented on components/layout/Navigation.js
> +              <NavItem href="/Gallery">Galeria</NavItem>
``/about /gallery``, don't uppercase

2023-10-12 10:01 UTC, Afan417 commented on components/sections/AboutSection.js
> +      {/* <HeaderTitle /> */}
do you need this now? if no remove it

2023-10-12 10:01 UTC, Afan417 commented on components/sections/AboutSection.js
> +          <Link className="py-5" href="/About">
``/About,`` no, use ``/about``

2023-10-12 11:53 UTC, Afan417 approved these changes

2023-10-12 11:54 UTC, merged